name: Try Comment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: STAGING
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on PR with Docker image tag
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello'
            })
