name: Try Comment

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Allow write access to pull requests
      contents: read  # Allow read access to repository contents
      id-token: write  # Allow write access to the ID token
    environment: STAGING
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Comment on PR with Docker image tag
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(`The event name is ${context.issue.number}`)
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
